server:
  port: 8090

spring:
  profiles:
    active: local



springdoc:
  group-configs:
    - group: all
      paths-to-match: /**

---
spring:
  config:
    activate:
      on-profile: local, test
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3307/semi
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    root: INFO
    com.multi.restproduct: DEBUG
    org.springframework.security: DEBUG

    # JDBC ?? ?? ????? ???????
    jdbc:
      resultset: OFF
      audit: OFF
      connection: OFF

